# This file was generated by GoReleaser. DO NOT EDIT.
cask "vrok" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "da73a5bbe3a790d652714156f0d670a8b7dd44914e3aa3724da84a20d7b548df"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "67fd5badc937ebc4b51174359fa34b1e517a3e6db56d035f4b10caac8aa440f1"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "abdbcf07fbedb9ad97c4719e2af9909dea07a370b04f684b1535eb63267b6007"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8b4c012501becc83e4686d6320ead061c4f688cdbb26eae3a234e8f25bc2bbb"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "vrok"
  desc "Share local files, folders and development servers through temporary URLs"
  homepage "https://github.com/AliJabbar034/vrok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vrok"
  bash_completion "completions/vrok.bash"
  fish_completion "completions/vrok.fish"
  zsh_completion "completions/vrok.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # Homebrew downloads over HTTPS, but Gatekeeper still quarantines
      # an unsigned binary; clearing it avoids a dialog on first run.
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vrok"]
    end
  end

  # No zap stanza required
end
