# This file was generated by GoReleaser. DO NOT EDIT.
cask "vrok" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/vrok"],
          must_succeed: false
    end
  end

  version "0.5.2"

  on_macos do
    on_arm do
      sha256 "63a6e6c2a3ce2a93d09a5b858c89c77afe7a9958563e81d5b7f54574671a7e47"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d9e28240d28fb6692492a6992a5bed0b3c586171ff877a63d9800cfcfbab282"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a566ccb3c92f6638628ce212e1c12e5f340c9c80df7ea9d12da8b8c2cf1f25ca"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "183d191eca1adf1d64be87e5c6b78279f11493e2587d4143b398d44259a50d17"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "vrok"
  desc "Share local files, folders and development servers through temporary URLs"
  homepage "https://github.com/AliJabbar034/vrok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vrok"
  bash_completion "completions/vrok.bash"
  fish_completion "completions/vrok.fish"
  zsh_completion "completions/vrok.zsh"

  # No zap stanza required
end
