# This file was generated by GoReleaser. DO NOT EDIT.
cask "vrok" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/vrok"],
          must_succeed: false
    end
  end

  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "b7298ca83a0ea13eeda6c9231541eef82c5d046e8367491ba1fa373c0ab0de94"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59ad4f09fedfc5b5766487339b104b7bef670b75bb7b104f4d5165d1ddcca99a"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "99318e77b6fb859b363df58ebd4205edea6ff0c5a375fdf519bca16240b53f35"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee9cc51bd70dc3d22e0ca403f33121cd86f9d522e1f3c1a162541e7ec5309890"
      url "https://github.com/AliJabbar034/vrok/releases/download/v#{version}/vrok_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "vrok"
  desc "Share local files, folders and development servers through temporary URLs"
  homepage "https://github.com/AliJabbar034/vrok"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vrok"
  bash_completion "completions/vrok.bash"
  fish_completion "completions/vrok.fish"
  zsh_completion "completions/vrok.zsh"

  # No zap stanza required
end
